export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const SET_USER_DATA_SUCCESS = "SET_USER_DATA_SUCCESS";
export const SET_USER_DATA_ERROR = "SET_USER_DATA_ERROR";

export const SEARCH_BY_STATE_SUCCESS = "SEARCH_BY_STATE_SUCCESS";
export const SEARCH_BY_STATE_ERROR = "SEARCH_BY_STATE_ERROR";

export const SEARCH_BY_CITY_SUCCESS = "SEARCH_BY_CITY_SUCCESS";
export const SEARCH_BY_CITY_ERROR = "SEARCH_BY_CITY_ERROR";

export const UPDATE_FILTER_RESULT = "UPDATE_FILTER_RESULT";

export const SET_BOOKING_DATA = "SET_BOOKING_DATA";

